// Modal Types
export const SET_OPEN_NFT_CREATE_MODAL = "SET_OPEN_NFT_CREATE_MODAL";
export const SET_WEB3_MODAL = "SET_WEB3_MODAL";
export const SET_SETTING_UP_NFT_MODAL = "SET_SETTING_UP_NFT_MODAL";
export const SET_CREATE_COLLECTION_MODAL = "SET_CREATE_COLLECTION_MODAL";
export const SET_SHARE_CREATED_NFT_MODAL = "SET_SHARE_CREATED_NFT_MODAL";

//Wallet Connection Types
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_WALLET_INFO = "UPDATE_WALLET_INFO";
export const SET_WALLET_CONNECTION_STATUS = "UPDATE_USER_BALANCE";

//auth
export const SET_SEND_EMAIL_STATUS = "SET_SEND_EMAIL_STATUS";
